// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdqeyneudhzeyufdqrxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcWV5bmV1ZGh6ZXl1ZmRxcnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjUwOTEsImV4cCI6MjA2NTQ0MTA5MX0.Mi1EQuM4Z5hjc2IGvTwe7jCaIhw56nXLkyZ9kRrhzU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);